// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "mm-plugin-gofile-btn",
  "name": "GoFile Button",
  "description": "Add a link button for GoFile to the channel header",
  "homepage_url": "https://github.com/ecator/mm-plugin-gofile-btn",
  "support_url": "https://github.com/ecator/mm-plugin-gofile-btn/issues",
  "release_notes_url": "https://github.com/ecator/mm-plugin-gofile-btn/releases",
  "icon_path": "assets/dog.svg",
  "version": "0.2.1",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "url",
        "display_name": "The url of GoFile",
        "type": "text",
        "help_text": "The url that will be jumped to",
        "placeholder": "http://gofile.example.com",
        "default": null
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
